--Creacion de tabla records dentro de staging para analizar datos crudos
-- Ejecutar conectado a: analisis_contrataciones_publicas

CREATE TABLE IF NOT EXISTS staging.records(
	ocid 										TEXT, -- identificador unico del proceso
	release_id 								    TEXT,
	release_tag									TEXT,
	release_date								TEXT,
	release_ocid								TEXT,
	release_publishdate							TEXT,
	release_initiationtype						TEXT,	 
	release_buyerid								TEXT,
	release_buyername							TEXT,
	release_planning_budget_description 		TEXT,
	release_planning_budget_amount_amount		TEXT,
	release_planning_budget_amount_currency		TEXT,
	release_planning_budget_amount_currencyname	TEXT,
	release_tender_id							TEXT,
	release_tender_title						TEXT,
	release_tender_description					TEXT,
	release_tender_procuringentity_id			TEXT,
	release_tender_procuringentity_name			TEXT,
	release_tender_datepublished				TEXT,
	release_tender_procurementmethoddetails		TEXT,
	release_tender_mainprocurementcategory		TEXT,
	release_tender_additionalprocurementcategories	TEXT,
	release_tender_value_amount					TEXT,
	release_tender_value_currency				TEXT,
	release_tender_value_currencyname			TEXT,
	release_tender_value_amount_pen 			TEXT,
	release_tender_tenderperiod_startdate		TEXT,
	release_tender_tenderperiod_enddate			TEXT,
	release_tender_enquiryperiod_startdate		TEXT,
	release_tender_enquiryperiod_enddate		TEXT,
	release_tender_enquiryperiod_durationindays	TEXT,
	release_tender_hastenderinformationprotectedbylaw	TEXT,
	release_tender_numberoftenderers			TEXT,
	release_datasegmentation_id					TEXT,
	release_datasegmentation_criteria			TEXT,
	release_planning_budget_project				TEXT,
	release_planning_budget_projectid			TEXT,
	release_tender_procurementmethod			TEXT,
	release_tender_tenderperiod_durationindays	TEXT
);